### ISSUE TITLE
Error when exclude-from-classmap points to non-existing folder

### ISSUE THREAD

**Issue by joppuyo** [TypistTech/imposter-plugin#119]
Hey, I'm having problem with installing [Symfony\Process](https://github.com/symfony/process) package.

It has the following line in [composer.json](https://github.com/symfony/process/blob/e4eb5b2a6fb287cf40282587c591bac566c2ed78/composer.json):

```    
    "autoload": {
        "psr-4": { "Symfony\\Component\\Process\\": "" },
        "exclude-from-classmap": [
            "/Tests/"
        ]
    },
```

It looks like the Composer distribution does not include this `Test` folder which causes the following error:

```
 [UnexpectedValueException]                                                                                                                                                                        
  RecursiveDirectoryIterator::__construct(/Users/johannessiipola/Documents/Projects/searchwp-finnish-base-forms-new-local/app/public/wp-content/plugins/searchwp-finnish-base-forms/vendor/symfony  
  /process//Tests/): failed to open dir: No such file or directory         
```

I can prevent this error either by creating this folder or removing the line from the package's composer.json.

**Comment by joppuyo** [comment]
I have temporarily fixed this by adding the following to my Composer scripts to create this folder.

```
    "scripts": {
        "pre-update-cmd": [
            "mkdir -p vendor/symfony/Process/Tests"
        ]
    }
```

**Comment by alessandromorelli** [comment]
This error is caused by the `exclude-from-classmap` entries.

The last release (0.6.0) should fix this particular case.

**Comment by TangRufus** [comment]
Thanks @alessandromorelli 

@joppuyo Reopen if v0.6 still failling.
